export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const WHOAMI_REQUEST = 'WHOAMI_REQUEST';
export const WHOAMI_SUCCESS = 'WHOAMI_SUCCESS';
export const WHOAMI_ERROR = 'WHOAMI_ERROR';

export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';

export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_ERROR = 'CREATE_CHAT_ERROR';

export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_ERROR = 'GET_CHATS_ERROR';

export const JOIN_CHAT_REQUEST = 'JOIN_CHAT_REQUEST';
export const JOIN_CHAT_SUCCESS = 'JOIN_CHAT_SUCCESS';
export const JOIN_CHAT_ERROR = 'JOIN_CHAT_ERROR';

export const LEAVE_CHAT_REQUEST = 'LEAVE_CHAT_REQUEST';
export const LEAVE_CHAT_SUCCESS = 'LEAVE_CHAT_SUCCESS';
export const LEAVE_CHAT_ERROR = 'LEAVE_CHAT_ERROR';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_ERROR = 'DELETE_CHAT_ERROR';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';

export const SHOW_ALL_CHATS = 'SHOW_ALL_CHATS';
export const SHOW_MY_CHATS = 'SHOW_MY_CHATS';

export const CHAT_QUERY_CHANGE = 'CHAT_QUERY_CHANGE';

export const SOCKET_CONNECTION_REQUEST = 'SOCKET_CONNECTION_REQUEST';

export const NEW_CHAT_EVENT = 'NEW_CHAT_EVENT';